tumSehirler = ["Adana",
               "Adıyaman",
               "Afyonkarahisar",
               "Ağrı",
               "Amasya",
               "Ankara",
               "Antalya",
               "Artvin",
               "Aydın",
               "Balıkesir",
               "Bilecik",
               "Bingöl",
               "Bitlis",
               "Bolu",
               "Burdur",
               "Bursa",
               "Çanakkale",
               "Çankırı",
               "Çorum",
               "Denizli",
               "Diyarbakır",
               "Edirne",
               "Elazığ",
               "Erzincan",
               "Erzurum",
               "Eskişehir",
               "Gaziantep",
               "Giresun",
               "Gümüşhane",
               "Hakkari",
               "Hatay",
               "Isparta",
               "Mersin",
               "İstanbul",
               "İzmir",
               "Kars",
               "Kastamonu",
               "Kayseri",
               "Kırklareli",
               "Kırşehir",
               "Kocaeli",
               "Konya",
               "Kütahya",
               "Malatya",
               "Manisa",
               "Kahramanmaraş",
               "Mardin",
               "Muğla",
               "Muş",
               "Nevşehir",
               "Niğde",
               "Ordu",
               "Rize",
               "Sakarya",
               "Samsun",
               "Siirt",
               "Sinop",
               "Sivas",
               "Tekirdağ",
               "Tokat",
               "Trabzon",
               "Tunceli",
               "Şanlıurfa",
               "Uşak",
               "Van",
               "Yozgat",
               "Zonguldak",
               "Aksaray",
               "Bayburt",
               "Karaman",
               "Kırıkkale",
               "Batman",
               "Şırnak",
               "Bartın",
               "Ardahan",
               "Iğdır",
               "Yalova",
               "Karabük",
               "Kilis",
               "Osmaniye",
               "Düzce"
               ]

guneydoguAnadoluSehirleri = ["Adıyaman",
                             "Diyarbakır",
                             "Gaziantep",
                             "Mardin",
                             "Siirt",
                             "Şanlıurfa",
                             "Batman",
                             "Şırnak",
                             "Kilis"]

doguAnadoluSehirleri = ["Ağrı",
                        "Bingöl",
                        "Bitlis",
                        "Elazığ",
                        "Erzincan",
                        "Erzurum",
                        "Hakkari",
                        "Kars",
                        "Malatya",
                        "Muş",
                        "Tunceli",
                        "Van",
                        "Ardahan",
                        "Iğdır"]

icAnadoluSehirleri = ["Ankara",
                      "Çankırı",
                      "Eskişehir",
                      "Kayseri",
                      "Kırşehir",
                      "Konya",
                      "Nevşehir",
                      "Niğde",
                      "Sivas",
                      "Yozgat",
                      "Aksaray",
                      "Karaman",
                      "Kırıkkale"]

akdenizSehirleri = ["Adana",
                    "Antalya",
                    "Burdur",
                    "Hatay",
                    "Isparta",
                    "Mersin",
                    "Kahramanmaraş",
                    "Osmaniye"]

egeSehirleri = ["Afyonkarahisar",
                "Aydın",
                "Denizli",
                "İzmir",
                "Kütahya",
                "Manisa",
                "Muğla",
                "Uşak"]

marmaraSehirleri = ["Balıkesir",
                    "Bilecik",
                    "Bursa",
                    "Çanakkale",
                    "Edirne",
                    "İstanbul",
                    "Kırıkkale",
                    "Kocaeli",
                    "Sakarya",
                    "Tekirdağ",
                    "Yalova"]

karadenizSehirleri = ["Amasya",
                      "Artvin",
                      "Bolu",
                      "Çorum",
                      "Giresun",
                      "Gümüşhane",
                      "Kastamonu",
                      "Ordu",
                      "Rize",
                      "Samsun",
                      "Sinop",
                      "Tokat",
                      "Trabzon",
                      "Zonguldak",
                      "Bayburt",
                      "Bartın",
                      "Karabük",
                      "Düzce"]

bolgeler = ["Tüm Şehirler",
            "Marmara Bölgesi",
            "Karadeniz Bölgesi",
            "Ege Bölgesi",
            "Akdeniz Bölgesi",
            "İç Anadolu Bölgesi",
            "Doğu Anadolu Bölgesi",
            "Güneydoğu Anadolu Bölgesi"]

bolgeler2 = [marmaraSehirleri,
             karadenizSehirleri,
             egeSehirleri,
             akdenizSehirleri,
             icAnadoluSehirleri,
             doguAnadoluSehirleri,
             guneydoguAnadoluSehirleri]
